apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep-3
  name: dep-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep-3
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
