apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cip-dep-1
  name: cip-dep-1
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dep-1
  type: ClusterIP
status:
  loadBalancer: {}
