apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"RoleBinding","apiVersion":"rbac.authorization.k8s.io/v1","metadata":{"name":"permit-job-inspector","namespace":"rbac","creationTimestamp":null},"subjects":[{"kind":"ServiceAccount","name":"job-inspector","namespace":"rbac"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"job-inspector"}}
  creationTimestamp: null
  name: permit-job-inspector
  namespace: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-inspector
subjects:
- kind: ServiceAccount
  name: job-inspector
  namespace: rbac
