apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-scale
  name: nginx-scale
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-scale
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-scale
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
