apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    command: ["/bin/sh", "-c", "env"]
    ports:
    - containerPort: 80
    env:
    - name: OWNER
      valueFrom:
        configMapKeyRef:
          name: mycm
          key: owner
