apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-6
  name: nginx-6
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-6
    spec:
      containers:
      - image: nginx:1.19.5
        name: nginx
        resources: {}
status: {}
